package com.spetro.earn;

import android.os.Bundle;
import android.util.Log;
import android.webkit.WebSettings;
import android.webkit.WebView;

import com.getcapacitor.BridgeActivity;

/**
 * MainActivity — Spetro Earn Android Entry Point
 *
 * Extends Capacitor's BridgeActivity to load the React web app inside a WebView,
 * then injects the AndroidBridge JavaScript interface so the frontend can detect
 * the native environment and activate features like the Adjoe Playtime card.
 *
 * INSTALLATION:
 *   Copy this file to:
 *   android/app/src/main/java/com/spetro/earn/MainActivity.java
 *
 *   Replace the default MainActivity.java generated by `npx cap add android`.
 */
public class MainActivity extends BridgeActivity {

    private static final String TAG = "SpetroMain";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // BridgeActivity.onCreate() creates the Capacitor WebView and loads the app
        super.onCreate(savedInstanceState);

        // Inject AndroidBridge AFTER the bridge is created so the WebView exists
        injectAndroidBridge();
    }

    private void injectAndroidBridge() {
        WebView webView = getBridge().getWebView();

        // Tune WebView settings for optimal performance
        WebSettings settings = webView.getSettings();
        settings.setJavaScriptEnabled(true);
        settings.setDomStorageEnabled(true);
        settings.setMediaPlaybackRequiresUserGesture(false);
        settings.setCacheMode(WebSettings.LOAD_DEFAULT);
        settings.setAllowFileAccess(false);
        settings.setAllowContentAccess(false);

        // Inject the AndroidBridge interface.
        // After this call, JavaScript can access:  window.AndroidBridge.*
        // The isNativeApp() check in Offerwalls.jsx returns true because
        // typeof window.AndroidBridge !== 'undefined'
        webView.addJavascriptInterface(new AndroidBridge(this), "AndroidBridge");

        Log.d(TAG, "AndroidBridge injected — Adjoe Playtime card is now active");
    }
}
